version: '3.10'

services:
  app:
    container_name: easy_money
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: app_db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    expose:
      - 5432
    ports:
      - "5435:5432"

volumes:
  postgres_data:
    driver: local