# Generated by Django 3.2 on 2022-12-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="commision",
            new_name="commission",
        ),
    ]
